config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      @restaurant = Restaurant.find(params[:restaurant_id])
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <!-- Logo -->

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <!-- Links -->
        <%= link_to "Restaurants", restaurants_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Add a restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-link" %>

      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurant list</h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li>
      <%=link_to restaurant.name, restaurant_path(restaurant) %>
      - <%= restaurant.category.capitalize %>
    </li>
    <% end %>
  </ul>
  <%= link_to "Add a new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>
<div class="container">
  <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "add a new restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.category.capitalize %></p>
  <p><%= @restaurant.address %></p>
  <h3>Restaurant reviews</h3>
  <ul>
    <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %>
      - <%= review.rating %>
    </li>
    <% end %>
  </ul>
  <p><%= link_to 'Go back to list', restaurants_path %></p>
  <p><%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %></p>
</div>
<div class="container">
  <h1>Create a new review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a new review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Create a new review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a new review", class: "btn btn-primary" %>
  <% end %>
</div>